### ISSUE TITLE
'\n' doesn't work in welcomeMessage

### ISSUE THREAD

**Issue by Nathaniel-Han** [linuswillner/react-console-emulator#519]
I have looked at the Live Demo and I think there's already a way to break lines in welcomeMessage that I don't know. :(

**Comment by linuswillner** [comment]
Sorry for taking a long time to get back to you on this, it's been a bit busy over the past month with the ongoing situation. I just implemented terminal message styling over in #518, I'll look at this one next 👍

**Comment by linuswillner** [comment]
Besides, there is a way to put newlines in welcome messages, it's by passing each line separately in an array - see [the demo](https://github.com/js-rcon/react-console-emulator/blob/master/demo/App.jsx#L84-L87). Regardless of this, I'm still going to implement newline parsing to all command outputs, since it's an obviously useful feature.

**Comment by Nathaniel-Han** [comment]
thanks for your suggestion, I will try this trick :) @linuswillner

**Comment by linuswillner** [comment]
Apparently with GitHub having gone a bit haywire yesterday, the reference did not come through, but I implemented proper newline parsing in fd72a4edccfad020845d46ab7261b89dff5b9e3d. It's coming very soon in the v4.0.0 update 👍
