### ISSUE TITLE
this.terminal.current.pushToStdout allow to push react element

### ISSUE THREAD

**Issue by sinwailam193** [linuswillner/react-console-emulator#607]
Hello thank you for creating this library. Before on version 3.0.5, I was allow to push in react elements something like this:
`pushToStdout(<span className="style">message</span>);` which allowed me to style the message. However, after I upgraded to 4.0.1, I can no longer push element in. Even if I push react elements, it is converted into strings. Is there a way I can push in elements like before?

**Comment by sinwailam193** [comment]
I found a way to resolve it by converting the react element into string like so `pushToStdout("<span className="style">message</span>");`. Just curious if this is the intentional behavior.

**Comment by linuswillner** [comment]
Hi, this happens because the application works in the following way:

1. `pushToStdout()` takes a message and pushes it to the message array in component state.
2. `pushToStdout()` performs `setState()`.
3. Component updates, and renders the messages in the terminal to the effect of `this.state.messages.map(msg => <TerminalMessage>{msg}</TerminalMessage>)`.

See [the pushToStdout method](https://github.com/linuswillner/react-console-emulator/blob/master/src/Terminal.jsx#L80-L94) and how [getStdout is called in the component body](https://github.com/linuswillner/react-console-emulator/blob/master/src/Terminal.jsx#L243), which is just a call to [the getStdout method](https://github.com/linuswillner/react-console-emulator/blob/master/src/Terminal.jsx#L106-L119).

Elements don't get rendered because, per default, React renders items like this by appending `element.innerText` instead of `element.innerHTML` for security reasons, and this component inherently follows the same methodology. Because of this, the `pushToStdout()` function doesn't expect to receive anything except strings.

However, this behaviour can be overriden by setting the `dangerMode` prop to `true`, which renders the strings being pushed literally as HTML. The reason why it doesn't work if you just pass in a component is that you're actually trying to render a component object as HTML, which obviously doesn't work, and hence why you need to quote it as you demonstrated.

So, as far as I'm concerned, this is intentional behaviour 👍

**Comment by sinwailam193** [comment]
Thank you for the explanation, now it all make sense
